Fix serialization. Donation & Request relationship.
uprm-inso-4115-2019-2020-S2/semester-project-inso4115-DisasterAid-backend pull request #5
Opened 2020-05-07 20:54 UTC by Everod52

Added relationship to Donation with request

2020-05-07 20:57 UTC, yetsielaviles approved these changes

2020-05-07 21:16 UTC, jaortiz117 approved these changes

2020-05-07 21:28 UTC, jaortiz117 requested changes
Voy a hacer los cambios al donations dao

2020-05-07 21:45 UTC, Everod52 commented
> Voy a hacer los cambios al donations dao

No hay problema.

2020-05-07 23:01 UTC, Everod52 commented on dao/mixin.py
> +                #                          for i in value]
Delete commented code and TODO

2020-05-07 23:01 UTC, Everod52 commented on dao/request.py
> +
Add REQUEST_REQUIRED_PARAMS list

2020-05-07 23:42 UTC, Ale573 requested changes
When you add a donation to the system, the gets doesn't work for the user. There is a problem with the dictionary.

2020-05-08 14:33 UTC, Ale573 approved these changes
Everything is working. All the gets, posts, updates, and deletes for users and donations.

2020-05-10 01:57 UTC, javihernovoa approved these changes

2020-05-10 02:21 UTC, merged